# ===================================================================== #
#  An R package for Fast 'ggplot2' Plotting:                            #
#  https://github.com/msberends/plot2                                   #
#                                                                       #
#  This R package is free software; you can freely use and distribute   #
#  it for both personal and commercial purposes under the terms of the  #
#  GNU General Public License version 2.0 (GNU GPL-2), as published by  #
#  the Free Software Foundation.                                        #
#                                                                       #
#  We created this package for both routine data analysis and academic  #
#  research and it was publicly released in the hope that it will be    #
#  useful, but it comes WITHOUT ANY WARRANTY OR LIABILITY.              #
# ===================================================================== #

back2back_plot <- function(df,
                           x.title,
                           y.title,
                           category.title,
                           title,
                           subtitle,
                           caption,
                           tag,
                           title.linelength,
                           title.colour,
                           subtitle.linelength,
                           subtitle.colour,
                           na.replace,
                           na.rm,
                           facet.position,
                           facet.fill,
                           facet.bold,
                           facet.italic,
                           facet.size,
                           facet.margin,
                           facet.repeat_lbls_x,
                           facet.repeat_lbls_y,
                           facet.fixed_y,
                           facet.fixed_x,
                           facet.drop,
                           facet.nrow,
                           facet.relative,
                           x.date_breaks,
                           x.date_labels,
                           x.date_remove_years,
                           category.focus,
                           colour,
                           colour_fill,
                           colour_opacity,
                           x.lbl_angle,
                           x.lbl_align,
                           x.lbl_italic,
                           x.lbl_taxonomy,
                           x.remove,
                           x.position,
                           x.max_items,
                           x.max_txt,
                           category.max_items,
                           category.max_txt,
                           facet.max_items,
                           facet.max_txt,
                           x.breaks,
                           x.n_breaks,
                           x.transform,
                           x.expand,
                           x.limits,
                           x.labels,
                           x.character,
                           x.drop,
                           x.mic,
                           x.zoom,
                           y.remove,
                           y.24h,
                           y.age,
                           y.scientific,
                           y.percent,
                           y.percent_break,
                           y.breaks,
                           y.n_breaks,
                           y.limits,
                           y.labels,
                           y.expand,
                           y.transform,
                           y.position,
                           y.zoom,
                           y_secondary,
                           y_secondary.type,
                           y_secondary.title,
                           y_secondary.colour,
                           y_secondary.colour_fill,
                           y_secondary.scientific,
                           y_secondary.percent,
                           y_secondary.labels,
                           category.type,
                           category.labels,
                           category.percent,
                           category.breaks,
                           category.limits,
                           category.expand,
                           category.midpoint,
                           category.transform,
                           category.date_breaks,
                           category.date_labels,
                           category.character,
                           x.sort,
                           category.sort,
                           facet.sort,
                           x.complete,
                           category.complete,
                           facet.complete,
                           datalabels,
                           datalabels.round,
                           datalabels.format,
                           datalabels.colour,
                           datalabels.colour_fill,
                           datalabels.size,
                           datalabels.angle,
                           datalabels.lineheight,
                           decimal.mark,
                           big.mark,
                           summarise_function,
                           stacked,
                           stacked_fill,
                           horizontal,
                           reverse,
                           smooth,
                           smooth.method,
                           smooth.formula,
                           smooth.se,
                           smooth.level,
                           smooth.alpha,
                           smooth.linewidth,
                           smooth.linetype,
                           smooth.colour,
                           size,
                           linetype,
                           linewidth,
                           binwidth,
                           width,
                           jitter_seed,
                           violin_scale,
                           legend.position,
                           legend.title,
                           legend.reverse,
                           legend.nrow,
                           legend.barheight,
                           legend.barwidth,
                           legend.nbin,
                           legend.italic,
                           sankey.node_width,
                           sankey.node_whitespace,
                           sankey.alpha,
                           sankey.remove_axes,
                           zoom,
                           sep,
                           print,
                           text_factor,
                           font,
                           theme,
                           background,
                           markdown) {
  rlang::check_installed("patchwork", reason = "for back-to-back plots.")
  
  # do use facet.sort to allow order of facets
  facet_values <- as.character(unique(get_facet(df)))
  facet_values <- sort_data(facet_values, facet_values,
                            sort_method = facet.sort,
                            datapoints = facet_values,
                            summarise_function = NULL,
                            summarise_fn_name = "",
                            horizontal = TRUE,
                            drop = FALSE,
                            argument = "facet")
  facet_values <- as.character(levels(facet_values))
  
  df_left <- df |> filter(`_var_facet` == facet_values[1])
  df_right <- df |> filter(`_var_facet` == facet_values[2])
  
  x.title <- validate_title(x.title, markdown = markdown)
  y.title <- validate_title(y.title, markdown = markdown)
  title <- validate_title(title, markdown = markdown)
  subtitle <- validate_title(subtitle, markdown = markdown)
  caption <- validate_title(caption, markdown = markdown)
  if (isTRUE(y.title)) {
    y.title <- validate_title(get_y_name(df), markdown = isTRUE(markdown), df = df)
  }
  
  if (isTRUE(facet.fixed_x) || isTRUE(facet.fixed_y)) {
    plot2_caution("For fixed scales, set `y.limits` when using back-to-back plots")
  }
  
  # legend
  if (is.null(legend.position)) {
    if (has_category(df) && data_is_numeric(get_category(df))) {
      legend.position <- "right"
    } else {
      legend.position <- "top"
    }
  }
  legend.position <- validate_legend.position(legend.position)
  
  suppressMessages(
    left_plot <- df_left |>
      select(-starts_with("_var_")) |>
      plot2(x = !!str2lang(get_x_name(df)),
            y = !!get_y(df_left),
            category = !!(if (has_category(df)) str2lang(get_category_name(df)) else NULL),
            facet = !!facet_values[1],
            type = "col",
            horizontal = TRUE,
            x.title = NULL,
            y.transform = "reverse",
            title = NULL,
            subtitle = NULL,
            caption = NULL,
            x.position = "top", # move ticks to other side
            print = FALSE,
            facet.sort = NULL,
            legend.position = legend.position,
            y.title = y.title,
            na.replace = na.replace,
            na.rm = na.rm,
            facet.position = facet.position,
            facet.fill = facet.fill,
            facet.bold = facet.bold,
            facet.italic = facet.italic,
            facet.size = facet.size,
            facet.margin = facet.margin,
            x.date_breaks = x.date_breaks,
            x.date_labels = x.date_labels,
            x.date_remove_years = x.date_remove_years,
            category.focus = category.focus,
            colour = colour,
            colour_fill = colour_fill,
            colour_opacity = colour_opacity,
            x.lbl_angle = x.lbl_angle,
            x.lbl_align = x.lbl_align,
            x.lbl_italic = x.lbl_italic,
            x.lbl_taxonomy = x.lbl_taxonomy,
            x.remove = x.remove,
            x.max_items = x.max_items,
            x.max_txt = x.max_txt,
            category.max_items = category.max_items,
            category.max_txt = category.max_txt,
            x.breaks = x.breaks,
            x.n_breaks = x.n_breaks,
            x.transform = x.transform,
            x.expand = x.expand,
            x.limits = x.limits,
            x.labels = x.labels,
            x.character = x.character,
            x.drop = x.drop,
            x.mic = x.mic,
            x.zoom = x.zoom,
            y.remove = y.remove,
            y.24h = y.24h,
            y.age = y.age,
            y.scientific = y.scientific,
            y.percent = y.percent,
            y.percent_break = y.percent_break,
            y.breaks = y.breaks,
            y.n_breaks = y.n_breaks,
            y.limits = y.limits,
            y.labels = y.labels,
            y.expand = y.expand,
            y.position = y.position,
            y.zoom = y.zoom,
            category.type = category.type,
            category.labels = category.labels,
            category.percent = category.percent,
            category.breaks = category.breaks,
            category.limits = category.limits,
            category.expand = category.expand,
            category.midpoint = category.midpoint,
            category.transform = category.transform,
            category.date_breaks = category.date_breaks,
            category.date_labels = category.date_labels,
            category.character = category.character,
            x.sort = x.sort,
            category.sort = category.sort,
            x.complete = x.complete,
            category.complete = category.complete,
            datalabels = datalabels,
            datalabels.round = datalabels.round,
            datalabels.format = datalabels.format,
            datalabels.colour = datalabels.colour,
            datalabels.colour_fill = datalabels.colour_fill,
            datalabels.size = datalabels.size,
            datalabels.angle = datalabels.angle,
            datalabels.lineheight = datalabels.lineheight,
            decimal.mark = decimal.mark,
            big.mark = big.mark,
            summarise_function = summarise_function,
            stacked = stacked,
            stacked_fill = stacked_fill,
            reverse = reverse,
            smooth = smooth,
            smooth.method = smooth.method,
            smooth.formula = smooth.formula,
            smooth.se = smooth.se,
            smooth.level = smooth.level,
            smooth.alpha = smooth.alpha,
            smooth.linewidth = smooth.linewidth,
            smooth.linetype = smooth.linetype,
            smooth.colour = smooth.colour,
            size = size,
            linetype = linetype,
            linewidth = linewidth,
            binwidth = binwidth,
            width = width,
            jitter_seed = jitter_seed,
            violin_scale = violin_scale,
            legend.title = legend.title,
            legend.reverse = legend.reverse,
            legend.nrow = legend.nrow,
            legend.barheight = legend.barheight,
            legend.barwidth = legend.barwidth,
            legend.nbin = legend.nbin,
            legend.italic = legend.italic,
            sankey.node_width = sankey.node_width,
            sankey.node_whitespace = sankey.node_whitespace,
            sankey.alpha = sankey.alpha,
            sankey.remove_axes = sankey.remove_axes,
            zoom = zoom,
            sep = sep,
            text_factor = text_factor,
            font = font,
            theme = theme,
            background = background,
            markdown = markdown
      ) +
      theme(axis.text.y = element_blank(),
            plot.margin = margin(5,5,5,5))
  )
  
  suppressMessages(
    right_plot <- df_right |>
      select(-starts_with("_var_")) |>
      plot2(x = !!str2lang(get_x_name(df)),
            y = !!get_y(df_right),
            category = !!(if (has_category(df)) str2lang(get_category_name(df)) else NULL),
            facet = !!facet_values[2],
            type = "col",
            horizontal = TRUE,
            x.title = NULL,
            y.transform = "identity",
            title = NULL,
            subtitle = NULL,
            caption = NULL,
            print = FALSE,
            facet.sort = NULL,
            legend.position = legend.position,
            y.title = y.title,
            na.replace = na.replace,
            na.rm = na.rm,
            facet.position = facet.position,
            facet.fill = facet.fill,
            facet.bold = facet.bold,
            facet.italic = facet.italic,
            facet.size = facet.size,
            facet.margin = facet.margin,
            x.date_breaks = x.date_breaks,
            x.date_labels = x.date_labels,
            x.date_remove_years = x.date_remove_years,
            category.focus = category.focus,
            colour = colour,
            colour_fill = colour_fill,
            colour_opacity = colour_opacity,
            x.lbl_angle = x.lbl_angle,
            x.lbl_align = x.lbl_align,
            x.lbl_italic = x.lbl_italic,
            x.lbl_taxonomy = x.lbl_taxonomy,
            x.remove = x.remove,
            x.max_items = x.max_items,
            x.max_txt = x.max_txt,
            category.max_items = category.max_items,
            category.max_txt = category.max_txt,
            x.breaks = x.breaks,
            x.n_breaks = x.n_breaks,
            x.transform = x.transform,
            x.expand = x.expand,
            x.limits = x.limits,
            x.labels = x.labels,
            x.character = x.character,
            x.drop = x.drop,
            x.mic = x.mic,
            x.zoom = x.zoom,
            y.remove = y.remove,
            y.24h = y.24h,
            y.age = y.age,
            y.scientific = y.scientific,
            y.percent = y.percent,
            y.percent_break = y.percent_break,
            y.breaks = y.breaks,
            y.n_breaks = y.n_breaks,
            y.limits = y.limits,
            y.labels = y.labels,
            y.expand = y.expand,
            y.position = y.position,
            y.zoom = y.zoom,
            category.type = category.type,
            category.labels = category.labels,
            category.percent = category.percent,
            category.breaks = category.breaks,
            category.limits = category.limits,
            category.expand = category.expand,
            category.midpoint = category.midpoint,
            category.transform = category.transform,
            category.date_breaks = category.date_breaks,
            category.date_labels = category.date_labels,
            category.character = category.character,
            x.sort = x.sort,
            category.sort = category.sort,
            x.complete = x.complete,
            category.complete = category.complete,
            datalabels = datalabels,
            datalabels.round = datalabels.round,
            datalabels.format = datalabels.format,
            datalabels.colour = datalabels.colour,
            datalabels.colour_fill = datalabels.colour_fill,
            datalabels.size = datalabels.size,
            datalabels.angle = datalabels.angle,
            datalabels.lineheight = datalabels.lineheight,
            decimal.mark = decimal.mark,
            big.mark = big.mark,
            summarise_function = summarise_function,
            stacked = stacked,
            stacked_fill = stacked_fill,
            reverse = reverse,
            smooth = smooth,
            smooth.method = smooth.method,
            smooth.formula = smooth.formula,
            smooth.se = smooth.se,
            smooth.level = smooth.level,
            smooth.alpha = smooth.alpha,
            smooth.linewidth = smooth.linewidth,
            smooth.linetype = smooth.linetype,
            smooth.colour = smooth.colour,
            size = size,
            linetype = linetype,
            linewidth = linewidth,
            binwidth = binwidth,
            width = width,
            jitter_seed = jitter_seed,
            violin_scale = violin_scale,
            legend.title = legend.title,
            legend.reverse = legend.reverse,
            legend.nrow = legend.nrow,
            legend.barheight = legend.barheight,
            legend.barwidth = legend.barwidth,
            legend.nbin = legend.nbin,
            legend.italic = legend.italic,
            sankey.node_width = sankey.node_width,
            sankey.node_whitespace = sankey.node_whitespace,
            sankey.alpha = sankey.alpha,
            sankey.remove_axes = sankey.remove_axes,
            zoom = zoom,
            sep = sep,
            text_factor = text_factor,
            font = font,
            theme = theme,
            background = background,
            markdown = markdown
      ) +
      theme(axis.text.y = element_text(hjust = 0.5,
                                       margin = margin(l = 10, r = 10)),
            plot.margin = margin(5, 5, 5, 0))
  )

  p <- patchwork::wrap_plots(left_plot,
                             right_plot,
                             nrow = 1) +
    patchwork::plot_layout(guides = "collect",
                           axis_titles = "collect") +
    patchwork::plot_annotation(title = title,
                               subtitle = subtitle,
                               caption = caption,
                               theme = validate_theme(theme, "geom_col",
                                                      background = background,
                                                      text_factor = text_factor,
                                                      font = font,
                                                      horizontal = TRUE,
                                                      x.remove = x.remove,
                                                      y.remove = y.remove,
                                                      x.lbl_angle = x.lbl_angle,
                                                      x.lbl_align = x.lbl_align,
                                                      x.lbl_italic = x.lbl_italic,
                                                      facet.fill = facet.fill,
                                                      facet.bold = facet.bold,
                                                      facet.italic = facet.italic,
                                                      facet.size = facet.size,
                                                      facet.margin = facet.margin,
                                                      legend.italic = legend.italic,
                                                      title.colour = title.colour,
                                                      subtitle.colour = subtitle.colour,
                                                      has_y_secondary = FALSE,
                                                      has_category = has_category(df),
                                                      col_y_primary = NULL,
                                                      col_y_secondary = NULL,
                                                      sankey.remove_axes = FALSE)) & 
    theme(legend.position = legend.position,
          legend.justification = "center",
          legend.direction = "horizontal")
  
  
  on.exit({
    throw_messages()
    clear_plot2_env()
  })
  
  # return plot ----
  if (isTRUE(print)) {
    print(p)
  } else {
    p
  }
}
